jobs:
- name: run-tests
  plan:
  - get: shared-pipeline
  - get: project-pipeline
  - get: source
    trigger: true
  - get: cloud-native-image
  - task: run-all-tests
    image: cloud-native-image
    file: shared-pipeline/tasks/run-tests.yml

- name: publish
  plan:
  - get: shared-pipeline
  - get: project-pipeline
  - get: source
    trigger: true
    passed: [run-tests]
  - get: cloud-native-image
  - task: publish
    image: cloud-native-image
    file: shared-pipeline/tasks/publish.yml
    params:
      project_dir: ((project-dir))
      artifact_repo_username: ((maven-central-username))
      artifact_repo_password: ((maven-central-password))
      artifact_repo_signing_key_id: ((maven-central-gpg-key-id))
      artifact_repo_signing_key_passphrase: ((maven-central-gpg-key-passphrase))
      artifact_repo_signing_key_secret_keys: ((maven-central-gpg-secret-keys))

- name: deploy-blue
  plan:
  - get: shared-pipeline
  - get: project-pipeline
  - get: source
    trigger: true
    passed: [publish]
  - get: cf-cli-image
  - task: deploy-blue
    image: cf-cli-image
    file: shared-pipeline/tasks/deploy-blue.yml
    params:
      project_dir: ((project-dir))
      artifact_repo_uri: ((artifact-snapshots-repo-uri))
      artifact_repo_name: ((artifact-snapshots-repo-name))
      pcf_app_name: ((pcf-app-name))
      pcf_api_endpoint: ((pcf-api-endpoint))
      pcf_org_name: ((pcf-org-name))
      pcf_space_name: ((pcf-space-name))
      pcf_username: ((pcf-username))
      pcf_password: ((pcf-password))

resources:
- name: shared-pipeline
  type: git
  source:
    uri: ((shared-pipeline-git-repo-uri))
    branch: ((shared-pipeline-git-repo-branch))
    check: true
    ignore_paths: [README.md]
    private_key: ((shared-pipeline-git-repo-private-key))

- name: project-pipeline
  type: git
  source:
    uri: ((project-git-repo-uri))
    branch: ((project-git-repo-branch))
    check: true
    paths: [ci/*]
    ignore_paths: [gradle.properties, README.md]
    private_key: ((project-git-repo-private-key))

- name: source
  type: git
  source:
    uri: ((project-git-repo-uri))
    branch: ((project-git-repo-branch))
    check: true
    ignore_paths: [ci/*, gradle.properties, README.md]
    private_key: ((project-git-repo-private-key))

- name: cloud-native-image
  type: docker-image
  source:
    repository: opengoodio/cloud-native-kotlin-java-jdk-8-gradle

- name: cf-cli-image
  type: docker-image
  source:
    repository: opengoodio/cloud-native-cf-cli