---
platform: linux

params:
  env: dev
  pcf_app_name: No PCF App Name
  pcf_api_endpoint_uri: No PCF API Endpoint URI
  pcf_domain_name: No PCF Domain Name
  pcf_org_name: No PCF Org Name
  pcf_space_name: No PCF Space Name
  pcf_username: No PCF Username
  pcf_password: No PCF Password

inputs:
- name: shared-pipeline
- name: project-pipeline

run:
  path: shared-pipeline/tasks/rollback-green.sh