---
platform: linux

params:
  env: dev
  pcf_app_name: No PCF App Name
  pcf_domain_name: No PCF Domain Name
  health_check_endpoint_uri_template: https://app.domain/actuator/health
  version_check_endpoint_uri_template: https://app.domain/actuator/info
  smoke_tests_task_script: no-script.sh

inputs:
- name: shared-pipeline
- name: project-pipeline
- name: source

run:
  path: shared-pipeline/tasks/smoke-tests.sh